# Generated by Django 2.1.2 on 2018-11-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='agree',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='disagree',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='dislikes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='poll',
            name='likes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
