# Generated by Django 2.1.2 on 2018-11-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181107_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='agree',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='disagree',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='statement',
            field=models.CharField(max_length=500),
        ),
    ]
